export const ADD_SLIDE = "ADD_SLIDE";
export const DELETE_SLIDE = "DELETE_SLIDE";
export const CHANGE_CURRENT_SLIDE = "CHANGE_CURRENT_SLIDE";
export const SET_FABRIC_OBJECTS_IN_CURSLIDE = "SET_FABRIC_OBJECTS_IN_CURSLIDE";
