export const ADD_SLIDE = "ADD_SLIDE";
export const DELETE_SLIDE = "DELETE_SLIDE";
export const CHANGE_CURRENT_SLIDE = "CHANGE_CURRENT_SLIDE";
export const SET_FABRIC_OBJECTS_IN_CURSLIDE = "SET_FABRIC_OBJECTS_IN_CURSLIDE";

export const ADD_ITEM_IN_CURSLIDE = "ADD_ITEM_IN_CURSLIDE";
export const UPDATE_ITEM_IN_CURSLIDE = "UPDATE_ITEM_IN_CURSLIDE";
export const DELETE_ITEM_FROM_CURSLIDE = "DELETE_ITEM_FROM_CURSLIDE";
export const CHANGE_PAGE_COUNT_IN_CURSLIDE = "CHANGE_PAGE_COUNT_IN_CURSLIDE";
export const CLEAR_SLIDE = "CLEAR_SLIDE";

export const CHANGE_CANVAS_OPTION = "CHANGE_CANVAS_OPTION";
